//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenimKitaplığım.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKITAP
    {
        public int KITAPID { get; set; }
        public string AD { get; set; }
        public string SAYFA { get; set; }
        public string YAZAR { get; set; }
        public Nullable<int> KATEGORI { get; set; }
    
        public virtual TBLKATEGORİ TBLKATEGORİ { get; set; }
    }
}
